# Generated by Django 5.1.3 on 2024-11-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StressInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snoring_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('limb_movement', models.FloatField()),
                ('blood_oxygen_level', models.FloatField()),
                ('eye_movement', models.FloatField()),
                ('sleeping_hours', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('stress_level', models.IntegerField(choices=[(0, 'No Stress'), (1, 'Stress')])),
            ],
        ),
    ]
